### ISSUE TITLE
Replace ',' with '/' needed to make it work

### ISSUE THREAD

**Issue by funkydunc** [entozoon/html-includes#12]
Thanks for a great useful package.

I apologize if this is user error but the only way I was able to make this work was by adding this line into 
node_modules/bin/compile.js

line 98, before console.log(filePath)
```
filePath = filePath.replace(',','/')
```

Here was my scenario. I'm using the package to add common '_header.html' and '_footer.html' to a file called 'dashboard.html'

I have 2 directories:
user_interface/src/UserGuideFiles containing the 3 files listed above
user_interface/src/UserGuideDest for the output

in my package.json, in my 'scripts' object
```
"compile": "html-includes --src src/UserGuideFiles --dest src/UserGuideDist"
```

Before the fix, I get this error:

Error: ENOENT: no such file or directory, open 'c:\(full path to project)\user_interface\src,UserGuideFiles\_header.html'

after the fix the ',' is replaced with '/' and it works and the output is:

Reading: src/UserGuideFiles/_footer.html
Reading: src/UserGuideFiles/_header.html
Reading: src/UserGuideFiles/dashboard.html
src/UserGuideFiles/./_header.html
src/UserGuideFiles/./_footer.html
Saving: src/UserGuideFiles/dashboard.html-> src/UserGuideDist/dashboard.html

And the full file is written as expected

Thanks

**Comment by entozoon** [comment]
Hey @funkydunc, thank you for posting this issue.

It's very likely due to some buggy code that was recently [fixed](https://github.com/entozoon/html-includes/commit/e8b9dcbd05bbc79d15e6696c381fcf0f9641b29e).

Would you kindly try updating the package and trying again?
I have republished as version `3.1.0` - get that to make sure you're up to date

**Comment by funkydunc** [comment]
Hey @entozoon 

Got 3.1.0 and its working great now

Many thanks

**Comment by entozoon** [comment]
Wonderful!
