### ISSUE TITLE
Recreate src directory structure in dist

### ISSUE THREAD

**Issue by rensa** [entozoon/html-includes#13]
Hi there! I'm really enjoying this module, but I'm having a problem with 3.1.0 where all rendered files end up in the root of the `dist` directory regardless of how far down inside `src` they are. This causes files to overwrite each other. For example, in `package.json`:

```
"build": html-includes --src src --dest dist
```

And when I `npm run build`:

```
Reading: src/_footer.html
Reading: src/_head_imports.html
Reading: src/_navheader.html
Reading: src/index.html
Saving: src/index.html-> dist/index.html
Reading: src/learn/index.html
Saving: src/learn/index.html-> dist/index.html
```

Is it possible for `html-imports` to create the required subdirectories in `dist` as required (or even to just get the files to the right subdirectory if those subdirectories exist)? Thanks!

**Comment by entozoon** [comment]
https://github.com/entozoon/html-includes/commit/fff46c2a51aa853f6f755dfe7a7f9b79fdbb3e73 (note to self)

**Comment by rensa** [comment]
Holy moly, that was fast! This works a treat 😊

This is not a problem as far as my workflow is concerned (just requires some judicious use of `../`), but for a future minor version it would also be great be able to specify paths using absolute paths that are taken to be relative to the `src` directory, rather than assuming that all paths are relative to the given file.

I didn't get a chance to test out the parameter passing, but I'll have a play with it! Thanks again! 😀

**Comment by entozoon** [comment]
Good times!
You're very welcome, and thanks for the positive feedback.

Would you mind copy pasting that into a new issue? It's another great feature request idea.

PS: nice wordsmithing with 'judicious'
