### ISSUE TITLE
Specify require paths relative to src directory

### ISSUE THREAD

**Issue by rensa** [entozoon/html-includes#14]
With the 4.0.0 update, we can have files in subdirectories of `src` that are rendered in equivalent subdirectories of `dist`. That's fantastic, but one downside is that now the location of included files will vary according to the relative location of the source file.

Currently, as far as I can tell, all file paths in `require` statements are concatenated to the location of the _current_ file. Absolute paths, therefore, break. It'd be great if absolute paths were taken as relative to the `src` folder (or maybe the project root). For example, if my project directory is `~/Code/myproject` and the file being rendered is in `src/red/blue.html`:

Specified path | Resolved path | OK? | Desired path resolution 
-----|-----|--|------
`_header.html` | `~/Code/myproject/src/red/_header.html` | ✔ | `~/Code/myproject/src/red/_header.html`
`./_header.html` | `~/Code/myproject/src/red/./_header.html` | ✔ | `~/Code/myproject/src/red/./_header.html`
`/_header.html` | `~/Code/myproject/src/red//_header.html` | ❌ | `~/Code/myproject/src/_header.html`

How does that sound?

**Comment by entozoon** [comment]
Hey dude, thanks for the detailed issue. I had a [crack](https://github.com/entozoon/html-includes/commit/1f094caa5dfa118de5af778fd37e02229af551ab) at fixing it, but unfortunately it highlighted some bigger issues and I've hit a wall. might need a rewrite to some extent

**Comment by entozoon** [comment]
I have rewritten this package almost from scratch (😩!) and this issue should be resolved.

Please update to version `4.1.0` to try it, or see [HTML Includes Example](https://github.com/entozoon/html-includes-example) for a working test project.

If this bug still exists, pop a new issue report in and I'll see what I can do.
