### ISSUE TITLE
Props not working

### ISSUE THREAD

**Issue by wilvin** [entozoon/html-includes#17]
Hey Michael, I hope you’re doing well!

This plugin is very useful, thanks for sharing it.  I'm having an issue now when trying to use the props. I've been using this plugin for a while this year. And a few weeks ago tried to use the props feature.

For me is not working. I'm using the same example that you show in the documentation, but the output is <p>Main content **"The resulting value should be here"**</p> without the prop value in the compiled file. What do you think is happening?

**Comment by entozoon** [comment]
I am well, thank you @wilvin. And you know what, you're right; there is a bug.
Let me investigate for you

**Comment by entozoon** [comment]
I have rewritten this package almost from scratch (😩!) and this issue should be resolved.

Please update to version `4.1.0` to try it, or see [HTML Includes Example](https://github.com/entozoon/html-includes-example) for a working test project.

If this bug still exists, pop a new issue report in and I'll see what I can do.

**Comment by wilvin** [comment]
Ohhh wow. The whole thing? x_x

Thank you very much! You are very kind.

Have a nice rest of the day.
