### ISSUE TITLE
Other directories not copied into dist

### ISSUE THREAD

**Issue by arulrajnet** [entozoon/html-includes#18]
My folder structure is like this

src
  ├── css
  │   └── main.css
  ├── _footer.html
  ├── _footer_menu.html
  ├── images
  │   └── logo.png
  ├── index.html
  ├── js
  │   └── main.js
  ├── _menu.html
  ├── _meta.html
  └── _top_menu.html

In the dist folder only index.html files are copied. Other relative folders such as css, js and images are not copied.

**Comment by entozoon** [comment]
That's not something it claims to do. So I'll tag it as a feature request

**Comment by entozoon** [comment]
In the event that this doesn't get implemented, it might be advisable for you to check out [webpack](https://github.com/webpack/webpack) for more advanced features such as this
