### ISSUE TITLE
Can we remove the clear screen effect?

### ISSUE THREAD

**Issue by tsjensen** [entozoon/html-includes#19]
Thanks for this cool and useful tool!

Just a small request:
Would it be possible to remove the clear screen command from [line 54 of compile.js](https://github.com/entozoon/html-includes/blob/ad23aae108ecf7ce728d84a6aaf7140e9d3d5d8d/bin/compile.js#L54)?
It is a bit confusing because it hides the other log statements that came before (now I must scroll instead of seeing everything at once). Also, it messes up logs in my CI.

Or maybe the clear screen could be optional, for people who want to have it.

I appreciate your work - thank you!

**Comment by entozoon** [comment]
I think that's a legit request yeah, it doesn't really add much anyway.
Updated and publish with [4.1.1](https://github.com/entozoon/html-includes/commit/566a78837995b8225b5620aa4ad7af0c482387b5).
Thanks for using it and the tip! I'd happily review PRs too if you have other ideas

**Comment by tsjensen** [comment]
Great - thank you!  😎👍
