### ISSUE TITLE
Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by diederikeen** [entozoon/html-includes#20]
Whenever I try to include a file in a parent dir I get a error message saying
```
/Users/diederik/sites/loc.motion-delta.nl/node_modules/html-includes/bin/compile.js:111
let filesContent = files.filter(f => f.id == filesId)[0].content;

TypeError: Cannot read property 'content' of undefined at file.content.file.content.replace.require (/Users/diederik/sites/loc.motion-delta.nl/node_modules/html-includes/bin/compile.js:111:69)
```

And my code would be something like this:

`./src/html/contact/index.html` trying to included `./src/html/includes/_html-head.html`

```
${require('../includes/_html-head.html') pageTitle="Contact | My Project"}
```

**Comment by entozoon** [comment]
Hello there, thanks for the report!
Please kindly update to version [4.2.0](https://github.com/entozoon/html-includes/commit/658ccf9e9f959ed7c71c0e45542db1ef5a8db5ea) and try again.

You stumbled upon a bug, which is that referencing parent directories `../` wasn't working at all, sorry about that!

**Comment by diederikeen** [comment]
Ah thank you so much! Its an amazing package btw!

**Comment by entozoon** [comment]
That's what she said! 😉
You're very welcome, glad you like it
