### ISSUE TITLE
--watch not working

### ISSUE THREAD

**Issue by Rigel772** [entozoon/html-includes#29]
When I try running
`npm run compile --watch`
the --watch flag seems to make no difference, it just runs once like without it...
is there any special setting necessary?
Thanks

**Comment by Rigel772** [comment]
BTW
same apply to --minify flag...

**Comment by entozoon** [comment]
Sorry to hear that @Rigel772 . You're not quite running it in the right way.
There is an example project - please look at the [package scripts in this file](https://github.com/entozoon/html-includes-example/blob/master/package.json#L8)

And you will see how to add an npm run command to minify or watch.
