### ISSUE TITLE
Include-holding tag not being removed from output

### ISSUE THREAD

**Issue by hachre** [entozoon/html-includes#3]
Hi!

When I try to reproduce the examples given my output doesn't come out as:
```
<p>Hello</p>
<p>Footer stuff</p>
```

But instead as:
```
<p>Hello</p>
<div ><p>Footer stuff</p>
</div>
```

The input that went in was exactly as it was in your example:
```
<p>Hello</p>
<div include="_footer.html"></div>
```

I have used `npm install --save-dev html-includes` and `npm install -g html-includes` to install it and then ran `html-includes --src source --dest build` manually on the command line instead of using the `package.json` way. Could that change the result like this?

I'm using nodejs v9.2.1.

**Comment by entozoon** [comment]
Ah yes, you're absolutely right. The readme is wrong and I will update.
