### ISSUE TITLE
"env: node\r:" bug on Linux/Mac in version 4.2.1

### ISSUE THREAD

**Issue by peterjwest** [entozoon/html-includes#30]
Looks like since 4.2.0, windows style line endings have got into the `run.js` shell script.

**Comment by entozoon** [comment]
`run.js` hasn't really changed in a [long while](https://github.com/entozoon/html-includes/commits/master/bin/run.js), so if you're having an issue it doesn't pertain to that version.
That said, it does indeed contain CRLF line endings, which I guess causes you grief? 
I've altered them to LF and released `4.3.2`. Not a thousand percent sure Github actually respects the change, so please give it a go

**Comment by peterjwest** [comment]
Thanks for the super quick response, that fixed it!

Looks like that file was changed in Feb 2019, and 4.2.0 was released after that. I don't think Github is displaying changes to line endings, which is kinda frustrating!

**Comment by entozoon** [comment]
You're very welcome!
