### ISSUE TITLE
index.html in rootdir not created

### ISSUE THREAD

**Issue by Seriousness** [entozoon/html-includes#32]
Whilst I do understand the idea of dist/-folders I prefer my --dist to be .
Files are created as wanted, only index.html is said to be written but is not created.
Sadly my coding knowledge is not good enough to look over, please see this only as a hint, not a request for fixing ;)

**Comment by entozoon** [comment]
Okay, I can see why you might want that. 
Have you tried running it with `--dest "."` or `--dest ""` ? I feel like it should work actually.

I've tagged it as an enhancement anyway that someone might come and work on this feature

**Comment by Seriousness** [comment]
That is indeed strange, while I tried to recreate the error message from --dest "" it created me the index with using ".\" - I was sure to have tried it... cant see why it does work now. Sorry for interrupting!
