### ISSUE TITLE
Possibility of passing HTML tags in the props

### ISSUE THREAD

**Issue by mahdiyazdani** [entozoon/html-includes#34]
Great tool!
Would it be possible to pass on simple HTML tags as properties as well? As an example, I have tried passing an anchor tag using props, but it looks like the build process gets broken as soon as it encounters symbols like `=` or `"`.

```html
${require('./_main.html') foo="<a href='http://example.com'>Example</a>"}
```

**Comment by entozoon** [comment]
Glad you like it! Yeah that should work in theory. The regex for detecting these props is
```/\b([^\s]+)="[^\"]*"/gi``` and should come out [like this](https://regex101.com/r/CDZn15/1) but I'll have a go with the app soon as I can

**Comment by entozoon** [comment]
Ah! @mahdiyazdani  I figured it out, it was splitting the string wrongly later on and you were right, a `=` confused it.
Fix has been published to `4.4.2`

**Comment by mahdiyazdani** [comment]
I might be wrong, but as far as I have tested, it appears that the initial cause for the compiler to stop is that it encounters the equal sign from the HTML attribute property and assumes that it could be a nested prop that it has to process.

https://github.com/entozoon/html-includes/blob/d4ebde10c5605d090cdadd521990f859075e392c/bin/compile.js#L167

**Comment by mahdiyazdani** [comment]
Thank you @entozoon for the quick fix. I can confirm that it now works with one HTML tag provided as a single property, as it complies as expected.
On the other hand, I have discovered a couple of issues with your recent change:

1. If we pass a second HTML tag as a property, it won’t compile as expected.
2. The original functionality of the compiler with static content being passed is broken with the new regex introduced.

Example:
```
${require('./partials/_item.html') first="<a href='https://www.google.com'>Google</a>" second="<a href='https://www.msn.com'>MSN</a>"}
```

```
<p>${props.first}</p>
<p>${props.second}</p>
```

**Comment by entozoon** [comment]
Oh yeah you're right, thanks for spotting it, I'll have another play

**Comment by entozoon** [comment]
Hey again  @mahdiyazdani , I've fixed the issue but please note with this new `5.0.0` version, you need to use backticks. i.e.
```
${require('./partials/_item.html') first=`<a href='https://www.google.com'>Google</a>` second=`<a href='https://www.msn.com'>MSN</a>`}
```
