### ISSUE TITLE
Removing the Include tags

### ISSUE THREAD

**Issue by robert-m** [entozoon/html-includes#4]
Hi Michael! 
This is fantastic!! But is there any way to remove the holding include tags from the outputs?

For example;
scr = `<div include="/common/_footer.html"></div>`
dist = `<footer> This is a footer </footer>`

The current version is rendering `<div >` tags which aren't required. Any chance you can add the option to remove these please? 

Thanks!

**Comment by entozoon** [comment]
Hey there, I'm glad you like it!
Great feature request idea, thank you.
One issue that is that you might sometimes want the tag, such as if you had a `<div class="retain-this" src="_stuff.html"></div>` but .. then again maybe not.

Perhaps a good way to go could be something like:
`<replace src="_stuff.html"></replace>`
So it's obvious that the whole thing would get replaced. What do you reckon?

**Comment by robert-m** [comment]
There's definitely cases where `<div class="retain-this" src="_stuff.html"></div>` will be used so I wouldn't remove it, but in most cases retaining the holding tag isn't necessary.

I see no problems with using `<replace src="_stuff.html"></replace>` to replace the holding tag completely. Or maybe use something like `<include src="_stuff.html"></include>` and the `<replace>` tag can be used for conditional/variables feature down the track?

**Comment by baleeds** [comment]
Hi, I also agree that this would be a critical feature.  For example, injecting partials to the `<head>` tag, would require replacing the tags that import.

**Comment by entozoon** [comment]
You're right @baleeds, that's a good example.

I'll invest some time on this feature, possibly rewriting the parsing code using [cheerio](https://github.com/cheeriojs/cheerio) .

**Comment by amodelbello** [comment]
Hi Michael - I also am a fan of this little module. Super simple and useful but like @robert-m and @baleeds, I think it would be worth while to add the option to strip out the parent include tags. I just submitted a pull request https://github.com/entozoon/html-includes/pull/7. Let me know what you think. Works for my purposes, e.g. including content in <head>, or a list of <script> tags at the end of the body.

I was pretty much looking for something where I could write code as simple as this while still having a valid html document:
```html
<include source="_top.html"></include>
ALL MY CONTENT
<include source="_bottom.html"></include>
```
and it works for that now.

**Comment by entozoon** [comment]
Hey gang, I very much appreciate the feedback and the PR @amodelbello but have actually rewritten it with cheerio after taking all the suggestions into account.
If anyone wants to try the major updated version (2.0.0), I think you'll all be pleased. The new usage seems much more logical - https://github.com/entozoon/html-includes#use

Hopefully won't have too many teething bugs

**Comment by amodelbello** [comment]
Right on. I'll take a look. Thanks Michael.
